### ISSUE TITLE
Add `var`, `const` or `let` 

### ISSUE THREAD

**Issue by karlguillotte** [aljedaxi/database2ogr#1]
You should replace that variable global declaration to a local declaration here, declaring a variable this way leaks to the global object (the module in this case):

```js 
const geometry_row = 'geom'
```

https://github.com/aljedaxi/database2ogr/blob/75cdd7ea1162e7e2e0595ad6edc61884c24cafc0/get_GIS_by_area.js#L81

https://github.com/aljedaxi/database2ogr/blob/75cdd7ea1162e7e2e0595ad6edc61884c24cafc0/get_GIS_by_area.js#L238

**Comment by aljedaxi** [comment]
i'll change that and start using a linter
